import type { Metadata } from "next";
import { Geist, Geist_Mono, Gabarito, Amaranth } from "next/font/google";
import "./globals.css";

// Font imports
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  weight: "400",
  subsets: ["latin"],
});

const amaranth = Amaranth({
  variable: "--font-amaranth",
  weight: ["400"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gabarito.variable} ${amaranth.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
